export const spacesData = [
  {
    id: 1,
    category: "Residential",
    categories: ["Residential", "Retreat"],
    image: "/spaces/space-1.jpg",
    date: "June 10, 2021",
    name: "Desert Poolhouse",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Lakshmi+Narayanan&background=random",
    clientName: "Lakshmi Narayanan",
    route: "/sample-space",
  },
  {
    id: 2,
    category: "Residential",
    categories: ["Residential", "Cultural"],
    image: "/spaces/space-2.jpg",
    date: "May 15, 2021",
    name: "Sanctum Hall",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Karthik+Reddy&background=random",
    clientName: "Karthik Reddy",
    route: "/sample-space",
  },
  {
    id: 3,
    category: "Residential",
    categories: ["Residential", "Modern"],
    image: "/spaces/space-3.jpg",
    date: "April 22, 2021",
    name: "Arcade Residence",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Ananya+Iyer&background=random",
    clientName: "Ananya Iyer",
    route: "/sample-space",
  },
  {
    id: 4,
    category: "Commercial",
    categories: ["Commercial", "Gallery"],
    image: "/spaces/space-4.jpg",
    date: "March 8, 2021",
    name: "Atrium Gallery",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Arjun+Pillai&background=random",
    clientName: "Arjun Pillai",
    route: "/sample-space",
  },
  {
    id: 5,
    category: "Residential",
    categories: ["Residential", "Retreat"],
    image: "/spaces/space-5.jpg",
    date: "February 14, 2021",
    name: "Mountain Retreat",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Meera+Krishnan&background=random",
    clientName: "Meera Krishnan",
    route: "/sample-space",
  },
  {
    id: 6,
    category: "Commercial",
    categories: ["Commercial", "Cultural"],
    image: "/spaces/space-6.jpg",
    date: "January 30, 2021",
    name: "Horizon Pavilion",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Divya+Suresh&background=random",
    clientName: "Divya Suresh",
    route: "/sample-space",
  },
  {
    id: 7,
    category: "Hospitality",
    categories: ["Hospitality", "Wellness"],
    image: "/spaces/space-7.jpg",
    date: "December 12, 2020",
    name: "Lumen Spa",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Rahul+Menon&background=random",
    clientName: "Rahul Menon",
    route: "/sample-space",
  },
];
