export const spacesData = [
  {
    id: 1,
    category: "Residential",
    categories: ["Residential", "Retreat"],
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?q=80&w=2069&auto=format&fit=crop",
    date: "June 10, 2021",
    name: "Heritage Courtyard",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Lakshmi+Narayanan&background=random",
    clientName: "Lakshmi Narayanan",
    route: "/sample-space",
  },
  {
    id: 2,
    category: "Residential",
    categories: ["Residential", "Cultural"],
    image: "https://images.unsplash.com/photo-1628744448840-55bdb2497bd4?q=80&w=2070&auto=format&fit=crop",
    date: "May 15, 2021",
    name: "Tropical Veranda",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Karthik+Reddy&background=random",
    clientName: "Karthik Reddy",
    route: "/sample-space",
  },
  {
    id: 3,
    category: "Residential",
    categories: ["Residential", "Modern"],
    image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?q=80&w=2080&auto=format&fit=crop",
    date: "April 22, 2021",
    name: "Chettinad Villa",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Ananya+Iyer&background=random",
    clientName: "Ananya Iyer",
    route: "/sample-space",
  },
  {
    id: 4,
    category: "Commercial",
    categories: ["Commercial", "Gallery"],
    image: "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=2000&auto=format&fit=crop",
    date: "March 8, 2021",
    name: "Modern Malnad Home",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Arjun+Pillai&background=random",
    clientName: "Arjun Pillai",
    route: "/sample-space",
  },
  {
    id: 5,
    category: "Residential",
    categories: ["Residential", "Retreat"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=2070&auto=format&fit=crop",
    date: "February 14, 2021",
    name: "Hillside Retreat",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Meera+Krishnan&background=random",
    clientName: "Meera Krishnan",
    route: "/sample-space",
  },
  {
    id: 6,
    category: "Commercial",
    categories: ["Commercial", "Cultural"],
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
    date: "January 30, 2021",
    name: "Urban Oasis",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Divya+Suresh&background=random",
    clientName: "Divya Suresh",
    route: "/sample-space",
  },
  {
    id: 7,
    category: "Hospitality",
    categories: ["Hospitality", "Wellness"],
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=2070&auto=format&fit=crop",
    date: "December 12, 2020",
    name: "Skyline Heights Construction",
    location: "Bangalore, India",
    clientImage: "https://ui-avatars.com/api/?name=Rahul+Menon&background=random",
    clientName: "Rahul Menon",
    route: "/sample-space",
  },
];
