export const spacesData = [
  {
    id: 1,
    category: "Residential",
    categories: ["Residential", "Retreat"],
    image: "/spaces/space-1.jpg",
    date: "June 10, 2021",
    name: "Desert Poolhouse",
    location: "Greece, Athens",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "Marina Li",
    route: "/sample-space",
  },
  {
    id: 2,
    category: "Residential",
    categories: ["Residential", "Cultural"],
    image: "/spaces/space-2.jpg",
    date: "May 15, 2021",
    name: "Sanctum Hall",
    location: "Morocco, Marrakesh",
    clientImage: "/spaces/client-2.jpeg",
    clientName: "Alex Chen",
    route: "/sample-space",
  },
  {
    id: 3,
    category: "Residential",
    categories: ["Residential", "Modern"],
    image: "/spaces/space-3.jpg",
    date: "April 22, 2021",
    name: "Arcade Residence",
    location: "Portugal, Lisbon",
    clientImage: "/spaces/client-3.jpeg",
    clientName: "Sophia Rodriguez",
    route: "/sample-space",
  },
  {
    id: 4,
    category: "Commercial",
    categories: ["Commercial", "Gallery"],
    image: "/spaces/space-4.jpg",
    date: "March 8, 2021",
    name: "Atrium Gallery",
    location: "Austria, Vienna",
    clientImage: "/spaces/client-4.jpeg",
    clientName: "David Kim",
    route: "/sample-space",
  },
  {
    id: 5,
    category: "Residential",
    categories: ["Residential", "Retreat"],
    image: "/spaces/space-5.jpg",
    date: "February 14, 2021",
    name: "Mountain Retreat",
    location: "Switzerland, Zurich",
    clientImage: "/spaces/client-5.jpeg",
    clientName: "Emma Wilson",
    route: "/sample-space",
  },
  {
    id: 6,
    category: "Commercial",
    categories: ["Commercial", "Cultural"],
    image: "/spaces/space-6.jpg",
    date: "January 30, 2021",
    name: "Horizon Pavilion",
    location: "Japan, Kyoto",
    clientImage: "/spaces/client-6.jpeg",
    clientName: "Aiko Tanaka",
    route: "/sample-space",
  },
  {
    id: 7,
    category: "Hospitality",
    categories: ["Hospitality", "Wellness"],
    image: "/spaces/space-7.jpg",
    date: "December 12, 2020",
    name: "Lumen Spa",
    location: "UAE, Dubai",
    clientImage: "/spaces/client-7.jpeg",
    clientName: "Omar Rahman",
    route: "/sample-space",
  },
];
